#!/usr/bin/bash
# Very simple tool to help manage floods of PRs
for I in `gh pr list|cut -f 1`; do
    gh pr diff $I
    read -p"Accept $I? " foo
    if [[ "$foo" == "y" ]];
        then gh pr merge -m $I
    fi
    echo
done

